### ISSUE TITLE
Safari includes “bound ” in the name of bound functions.

### ISSUE THREAD

**Issue by mbostock** [observablehq/notebook-inspector#20]
Which… is weird.

```js
Promise.resolve.bind(Promise)
```
```
ƒ bound resolve()
```

And

```js
Promise.resolve.bind(Promise).name
```
```
"bound resolve"
```

But

```js
Promise.resolve.bind(Promise) + ""
```
```
`function resolve() {
    [native code]
}`
```

Not sure if we should workaround this or just let Safari be Safari.

**Comment by tmcw** [comment]
This actually looks pretty uniform - [MDN documents it](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name) and I can replicate in Chrome, Firefox, and Node that binding a method adds the `bound ` prefix to its name.

I think... we have no responsibility to be pedantic about showing functions with exactly what `function.name` gives us, and we should remove the `bound` prefix. Eh?

**Comment by tmcw** [comment]
Okay, we're following developer console precedent and keeping the `bound` in.
