### ISSUE TITLE
Make inspector available as value renderer

### ISSUE THREAD

**Issue by rumkin** [observablehq/notebook-inspector#33]
When I return JS value from a note it renders into inspectable, like this:

<img width="234" alt="screen shot 2018-11-05 at 19 20 26" src="https://user-images.githubusercontent.com/609373/48013047-7f97bd80-e134-11e8-8681-3cb90f5df4a0.png">

I want to create a custom view which can render such nice structures inside of it and use Observable's styles to look "native".

What I'm trying to do is to create custom table view which cells are inspectable views.

**Comment by tmcw** [comment]
Yep! We want this too, and plan on implementing it: the task is captured in the existing issue #14
